package permissions

const (
	// Server permissions
	ServersList                 = "servers.list"
	ServersGet                  = "servers.get"
	ServersCreate               = "servers.create"
	ServersUpdate               = "servers.update"
	ServersDelete               = "servers.delete"
	ServersTestConnection       = "servers.test_connection"
	ServersMetricsRead          = "servers.metrics.read"
	ServersMetricsLatest        = "servers.metrics.latest"
	ServersMetricsLive          = "servers.metrics.live"
	ServersActivityRead         = "servers.activity.read"
	ServersNodeExporterStatus   = "servers.node_exporter.status"
	ServersNodeExporterInstall  = "servers.node_exporter.install"
	ServersStart                = "servers.start"
	ServersStop                 = "servers.stop"
	ServersRestart              = "servers.restart"
	ServersStatusRead           = "servers.status.read"
	ServersConsoleView          = "servers.console.view"
	ServersConsoleExecute       = "servers.console.execute"
	ServersConsoleHistoryRead   = "servers.console.history.read"
	ServersConsoleHistorySearch = "servers.console.history.search"
	ServersConsoleAutocomplete  = "servers.console.autocomplete"
	ServersTasksRead            = "servers.tasks.read"
	ServersDependenciesInstall  = "servers.dependencies.install"
	ServersDependenciesCheck    = "servers.dependencies.check"
	ServersAgentInstall         = "servers.agent.install"
	ServersAgentStateRead       = "servers.agent.state.read"
	ServersProcessKill          = "servers.process.kill"
	ServersReleaseDeploy        = "servers.releases.deploy"
	ServersTransferBenchmark    = "servers.transfer.benchmark"

	// Server backups
	ServersBackupsCreate           = "servers.backups.create"
	ServersBackupsList             = "servers.backups.list"
	ServersBackupsGet              = "servers.backups.get"
	ServersBackupsRestore          = "servers.backups.restore"
	ServersBackupsDelete           = "servers.backups.delete"
	ServersBackupsRetentionEnforce = "servers.backups.retention.enforce"

	// Settings
	SettingsGet    = "settings.get"
	SettingsUpdate = "settings.update"

	// Releases
	ReleasesList              = "releases.list"
	ReleasesGet               = "releases.get"
	ReleasesJobsList          = "releases.jobs.list"
	ReleasesJobsGet           = "releases.jobs.get"
	ReleasesJobsStream        = "releases.jobs.stream"
	ReleasesDownload          = "releases.download"
	ReleasesDelete            = "releases.delete"
	ReleasesPrintVersion      = "releases.print_version"
	ReleasesCheckUpdate       = "releases.check_update"
	ReleasesDownloaderVersion = "releases.downloader_version"
	ReleasesResetAuth         = "releases.reset_auth"

	// IAM
	IAMUsersList              = "iam.users.list"
	IAMUsersGet               = "iam.users.get"
	IAMUsersCreate            = "iam.users.create"
	IAMUsersUpdate            = "iam.users.update"
	IAMUsersDelete            = "iam.users.delete"
	IAMUsersRolesUpdate       = "iam.users.roles.update"
	IAMRolesList              = "iam.roles.list"
	IAMRolesGet               = "iam.roles.get"
	IAMRolesCreate            = "iam.roles.create"
	IAMRolesUpdate            = "iam.roles.update"
	IAMRolesDelete            = "iam.roles.delete"
	IAMRolesPermissionsUpdate = "iam.roles.permissions.update"
	IAMPermissionsList        = "iam.permissions.list"
	IAMAuditLogsList          = "iam.audit_logs.list"
)
